import Head from 'next/head'
import './globals.css'
import { AuthProvider } from '@/hooks/useAuth'
import { Provider } from 'react-redux'
import store from '@/redux/store/store'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'nike-ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (

    <html lang="en">
      <body>
        {/* <Provider store={store}> */}
          <AuthProvider >
            <ToastContainer
              position="top-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />

            {children}
          </AuthProvider>
        {/* </Provider> */}
      </body>
    </html>
  )
}
